check for a custom set "my-cmssw" remote

diff --git a/git-cms-init b/git-cms-init
--- a/git-cms-init
+++ b/git-cms-init
@@ -22,7 +22,8 @@ usage () {
 }
 
 # configuration
-CHECK=0
+CHECK=
+CUSTOM_REMOTE=
 VERBOSE=1
 VERBOSE_STREAM=/dev/stderr
 DEBUG_STREAM=/dev/null
@@ -43,7 +44,7 @@ while [ "$#" != 0 ]; do
     -h | --help )
       usage 0;;
     --check )
-      shift; CHECK=1 ;;
+      shift; CHECK=true ;;
     -d | --debug )
       shift; set -x; DEBUG_STREAM=/dev/stderr ;;
     -q | --quiet | -z )
@@ -232,47 +233,68 @@ if [ -e $CMSSW_GIT_REFERENCE/create-`whoami` ]; then
   (cd $CMSSW_GIT_REFERENCE ;  git remote update origin 2>$VERBOSE_STREAM >$VERBOSE_STREAM)
 fi
 
-# check the user setup on GitHub
-if curl -s "https://api.github.com/users/$GITHUB_USERNAME" | tee $DEBUG_STREAM | grep -q -i 'Not Found' ; then
-  $ECHO "You don't seem to have a GitHub accout, or your GitHub username ($RED$GITHUB_USERNAME$NORMAL) is not correct." > $VERBOSE_STREAM
-  $ECHO "($RED$GITHUB_USERNAME$NORMAL) is not correct."                                                     > $VERBOSE_STREAM
-  $ECHO "You can work locally, but you will not be able to push your changes to GitHub for inclusion "      > $VERBOSE_STREAM
-  $ECHO "in the official CMSSW distribution."                                                               > $VERBOSE_STREAM
-  $ECHO ""                                                                                                  > $VERBOSE_STREAM
-  $ECHO "You can correct your GitHub user name via:"                                                        > $VERBOSE_STREAM
-  $ECHO ""                                                                                                  > $VERBOSE_STREAM
-  $ECHO "    git config --global user.github <your github username>"                                        > $VERBOSE_STREAM
-  $ECHO ""                                                                                                  > $VERBOSE_STREAM
-  $ECHO ""                                                                                                  > $VERBOSE_STREAM
-  $ECHO "To create a personal repository:"                                                                  > $VERBOSE_STREAM
-  $ECHO "    visit to https://github.com/ and register a new account"                                       > $VERBOSE_STREAM
-  $ECHO "    visit to https://github.com/cms-sw/cmssw and click on the Fork button"                         > $VERBOSE_STREAM
-  $ECHO "    select the option to fork the repository under your username ($RED$GITHUB_USERNAME$NORMAL)"    > $VERBOSE_STREAM
-  $ECHO ""                                                                                                  > $VERBOSE_STREAM
-  USER_CMSSW_REPO=""
-elif ! curl -s "https://api.github.com/users/$GITHUB_USERNAME/repos" | tee $DEBUG_STREAM | grep -q '"name": *"cmssw"'; then
-  $ECHO "You don't seem to have a personal repository, or your GitHub username ($RED$GITHUB_USERNAME$NORMAL) is not correct." > $VERBOSE_STREAM
-  $ECHO "You can work locally, but you will not be able to push your changes to GitHub for inclusion "      > $VERBOSE_STREAM
-  $ECHO "in the official CMSSW distribution."                                                               > $VERBOSE_STREAM
-  $ECHO ""                                                                                                  > $VERBOSE_STREAM
-  $ECHO "You can correct your GitHub user name via:"                                                        > $VERBOSE_STREAM
-  $ECHO ""                                                                                                  > $VERBOSE_STREAM
-  $ECHO "    git config --global user.github <your github username>"                                        > $VERBOSE_STREAM
-  $ECHO ""                                                                                                  > $VERBOSE_STREAM
-  $ECHO ""                                                                                                  > $VERBOSE_STREAM
-  $ECHO "To create a personal repository:"                                                                  > $VERBOSE_STREAM
-  $ECHO "  - go to https://github.com/ and log in"                                                          > $VERBOSE_STREAM
-  $ECHO "  - go to https://github.com/cms-sw/cmssw and click on the Fork button"                            > $VERBOSE_STREAM
-  $ECHO "  - select the option to fork the repository under your username ($RED$GITHUB_USERNAME$NORMAL)"    > $VERBOSE_STREAM
-  $ECHO ""                                                                                                  > $VERBOSE_STREAM
-  USER_CMSSW_REPO=""
-elif ((CHECK == 1)) && ! git ls-remote $USER_CMSSW_REPO >& $DEBUG_STREAM; then
-  $ECHO "Your GitHub account ($RED$GITHUB_USERNAME$NORMAL) and personal repository ($RED$USER_CMSSW_REPO$NORMAL) " > $VERBOSE_STREAM
-  $ECHO "look properly configured, but git is unable to access it."                                         > $VERBOSE_STREAM
-  $ECHO "You can work locally, but you will not be able to push your changes to GitHub for inclusion "      > $VERBOSE_STREAM
-  $ECHO "in the official CMSSW distribution."                                                               > $VERBOSE_STREAM
-  $ECHO ""                                                                                                  > $VERBOSE_STREAM
-  USER_CMSSW_REPO=""
+# check if the user has explicitly configured a remote repository
+if git config remote.origin.url >& /dev/null; then
+  USER_CMSSW_REPO=`git config remote.origin.url`
+  CUSTOM_REMOTE=true
+
+  if [ "X$USE_HTTPS_ACCESS_METHOD" = Xtrue ]; then
+    $ECHO "Attention: the --https option will be ignored since you have explicitly configured a"              > $VERBOSE_STREAM
+    $ECHO "'my-cmssw' remote repository: $RED$USER_CMSSW_REPO$NORMAL"                                         > $VERBOSE_STREAM
+  fi
+
+  if [ "$CHECK" ] && ! git ls-remote $USER_CMSSW_REPO >& $DEBUG_STREAM; then
+    $ECHO "Attention: git is unable to access your 'my-cmssw' remote repository ($RED$USER_CMSSW_REPO$NORMAL). " > $VERBOSE_STREAM
+    $ECHO "You can work locally, but you will not be able to push your changes to it."                        > $VERBOSE_STREAM
+    $ECHO ""                                                                                                  > $VERBOSE_STREAM
+    USER_CMSSW_REPO=""
+  fi
+
+else
+
+  # check the user setup on GitHub
+  if curl -s "https://api.github.com/users/$GITHUB_USERNAME" | tee $DEBUG_STREAM | grep -q -i 'Not Found' ; then
+    $ECHO "You don't seem to have a GitHub accout, or your GitHub username ($RED$GITHUB_USERNAME$NORMAL) is not correct." > $VERBOSE_STREAM
+    $ECHO "($RED$GITHUB_USERNAME$NORMAL) is not correct."                                                     > $VERBOSE_STREAM
+    $ECHO "You can work locally, but you will not be able to push your changes to GitHub for inclusion "      > $VERBOSE_STREAM
+    $ECHO "in the official CMSSW distribution."                                                               > $VERBOSE_STREAM
+    $ECHO ""                                                                                                  > $VERBOSE_STREAM
+    $ECHO "You can correct your GitHub user name via:"                                                        > $VERBOSE_STREAM
+    $ECHO ""                                                                                                  > $VERBOSE_STREAM
+    $ECHO "    git config --global user.github <your github username>"                                        > $VERBOSE_STREAM
+    $ECHO ""                                                                                                  > $VERBOSE_STREAM
+    $ECHO ""                                                                                                  > $VERBOSE_STREAM
+    $ECHO "To create a personal repository:"                                                                  > $VERBOSE_STREAM
+    $ECHO "    visit to https://github.com/ and register a new account"                                       > $VERBOSE_STREAM
+    $ECHO "    visit to https://github.com/cms-sw/cmssw and click on the Fork button"                         > $VERBOSE_STREAM
+    $ECHO "    select the option to fork the repository under your username ($RED$GITHUB_USERNAME$NORMAL)"    > $VERBOSE_STREAM
+    $ECHO ""                                                                                                  > $VERBOSE_STREAM
+    USER_CMSSW_REPO=""
+  elif ! curl -s "https://api.github.com/users/$GITHUB_USERNAME/repos" | tee $DEBUG_STREAM | grep -q '"name": *"cmssw"'; then
+    $ECHO "You don't seem to have a personal repository, or your GitHub username ($RED$GITHUB_USERNAME$NORMAL) is not correct." > $VERBOSE_STREAM
+    $ECHO "You can work locally, but you will not be able to push your changes to GitHub for inclusion "      > $VERBOSE_STREAM
+    $ECHO "in the official CMSSW distribution."                                                               > $VERBOSE_STREAM
+    $ECHO ""                                                                                                  > $VERBOSE_STREAM
+    $ECHO "You can correct your GitHub user name via:"                                                        > $VERBOSE_STREAM
+    $ECHO ""                                                                                                  > $VERBOSE_STREAM
+    $ECHO "    git config --global user.github <your github username>"                                        > $VERBOSE_STREAM
+    $ECHO ""                                                                                                  > $VERBOSE_STREAM
+    $ECHO ""                                                                                                  > $VERBOSE_STREAM
+    $ECHO "To create a personal repository:"                                                                  > $VERBOSE_STREAM
+    $ECHO "  - go to https://github.com/ and log in"                                                          > $VERBOSE_STREAM
+    $ECHO "  - go to https://github.com/cms-sw/cmssw and click on the Fork button"                            > $VERBOSE_STREAM
+    $ECHO "  - select the option to fork the repository under your username ($RED$GITHUB_USERNAME$NORMAL)"    > $VERBOSE_STREAM
+    $ECHO ""                                                                                                  > $VERBOSE_STREAM
+    USER_CMSSW_REPO=""
+  elif [ "$CHECK" ] && ! git ls-remote $USER_CMSSW_REPO >& $DEBUG_STREAM; then
+    $ECHO "Attention: your GitHub account ($RED$GITHUB_USERNAME$NORMAL) and personal repository ($RED$USER_CMSSW_REPO$NORMAL) " > $VERBOSE_STREAM
+    $ECHO "are properly configured, but git is unable to access it."                                          > $VERBOSE_STREAM
+    $ECHO "You can work locally, but you will not be able to push your changes to GitHub for inclusion "      > $VERBOSE_STREAM
+    $ECHO "in the official CMSSW distribution."                                                               > $VERBOSE_STREAM
+    $ECHO ""                                                                                                  > $VERBOSE_STREAM
+    USER_CMSSW_REPO=""
+  fi
+
 fi
 
 mkdir -p $CMSSW_BASE/src
@@ -296,8 +318,10 @@ if [ ! -d "$CMSSW_BASE/src/.git" ]; then
 
   # check if the user's remote repository exists
   if [ "$USER_CMSSW_REPO" ]; then
-    # add the user's remote repository
-    git remote add my-cmssw $USER_CMSSW_REPO
+    if ! [ "$CUSTOM_REMOTE" ]; then
+      # add the user's remote repository
+      git remote add my-cmssw $USER_CMSSW_REPO
+    fi
     git fetch my-cmssw                2> $VERBOSE_STREAM
     git fetch my-cmssw --tags         2> $VERBOSE_STREAM
   fi
