drop most of the functionality moved into git-cms-init, and read the default parameters from the git repository itself

diff --git a/git-cms-addpkg b/git-cms-addpkg
--- a/git-cms-addpkg
+++ b/git-cms-addpkg
@@ -46,10 +46,10 @@ while [ "$#" != 0 ]; do
       shift; ASSUME_YES=1 ;;
     --https )
       INITOPTIONS="$INITOPTIONS $1"
-      shift; USE_HTTPS_ACCESS_METHOD=true ;;
+      shift;;
     --ssh )
       INITOPTIONS="$INITOPTIONS $1"
-      shift; USE_SSH_ACCESS_METHOD=true ;;
+      shift;;
     -*)
       echo Unknown option $1 ; usage 1 ;;
     *)
@@ -65,148 +65,35 @@ while [ "$#" != 0 ]; do
   esac
 done
 
-GITHUB_USERNAME="`git config --global --get user.github || true`"
-if [ "X$GITHUB_USERNAME" = X ]; then
-  echo "Cannot find your GitHub information."
-  echo "Please register at"
-  echo
-  echo "https://github.com"
-  echo
-  echo "and then configure git via:"
-  echo
-  echo "git config --global user.github <your github username>"
-  exit 1
-fi
-USER_FULLNAME="`git config --global --get user.name || true`"
-if [ "X$USER_FULLNAME" = X ]; then
-  echo "Cannot find your name in git configuration."
-  echo "Please set it up via:"
-  echo
-  echo "git config --global user.name <your name> <your last name>"
-  exit 1
-fi
-USER_EMAIL="`git config --global --get user.email || true`"
-if [ "X$USER_EMAIL" = X ]; then
-  echo "Cannot find your email in git configuration."
-  echo "Please set it up via:"
-  echo
-  echo "git config --global user.email <your e-mail>"
-  exit 1
-fi
-
-
 if [ "X$PKG_NAME" = X ]; then
   echo "You need to specify at least one package." ; exit 1
 fi
 
-if [ "X$CMSSW_BASE" = X ]; then
-  if [ "X$CMSSW_TAG" = X ]; then
-    verbose CMSSW environment not setup. Do cmsenv in some workarea or specify tag to checkout.
-    exit 1
-  else
-    verbose Warning CMSSW environment not found. Checking out packages in $PWD/src.
-    CMSSW_BASE=$PWD
-  fi
-fi
+# initialize the local repository
+git cms-init $INITOPTIONS $CMSSW_TAG
+cd $CMSSW_BASE/src
 
-if [ "X$CMSSW_TAG" = X ]; then
-  verbose No release tags specified, using default $CMSSW_VERSION.
-  CMSSW_TAG=$CMSSW_VERSION
-fi
-
-CMSSW_BASE_BRANCH=`echo $CMSSW_TAG | sed -e 's/\(CMSSW_[0-9][0-9]*_[0-9][0-9]*\).*/\1/'`
-
-# SLHC releases
-case $CMSSW_TAG in
-  *_SLHC*)
-    SLHC=_SLHC ;;
-esac
-
-# This is not the case at FNAL. Disabling it for now.
-#IN_RELEASE=`echo $PWD | grep -q -e "^$CMSSW_BASE" 2> /dev/null && echo 1 || echo 0`
-#if [ "X$IN_RELEASE" = X0 ]; then
-#  OLD_CMSSW_BASE=$CMSSW_BASE
-#  eval `scram run -sh` >/dev/null
-#  IN_RELEASE=`echo $PWD | grep -q -e "^$CMSSW_BASE" 2> /dev/null && echo 1 || echo 0`
-#  if [ "X$IN_RELEASE" = X0 ]; then
-#    echo git cms-addpkg must be run from inside a CMSSW area.
-#    exit 1
-#  else
-#    echo Error: You have currently set up the environment of $OLD_CMSSW_BASE, however you are running inside $CMSSW_BASE.
-#    echo Please go inside $OLD_CMSSW_BASE, or use cmsenv to switch to $CMSSW_BASE.
-#    exit 1
-#  fi
-#fi
+GITHUB_USERNAME="`git config --global --get user.github || true`"
+USER_FULLNAME="`git config --global --get user.name || true`"
+USER_EMAIL="`git config --global --get user.email || true`"
 
 case `git --version` in
   git\ version\ 1.7*)
     OFFICIAL_CMSSW_REPO=git@github.com:cms-sw/cmssw.git
     USER_CMSSW_REPO=git@github.com:$GITHUB_USERNAME/cmssw.git
-    # git 1.7.x does not support a leading slash in /gitignore and .git/info/sparse-checkout
+    # git 1.7.x does not support a leading slash in .gitignore and .git/info/sparse-checkout
     LEADING_SLASH=
   ;;
   *)
-    if [ "X$USE_SSH_ACCESS_METHOD" = X ]; then
-      OFFICIAL_CMSSW_REPO=https://github.com/cms-sw/cmssw.git
-    else
-      OFFICIAL_CMSSW_REPO=git@github.com:cms-sw/cmssw.git
-    fi
-    if [ "X$USE_HTTPS_ACCESS_METHOD" = X ]; then
-      USER_CMSSW_REPO=git@github.com:$GITHUB_USERNAME/cmssw.git
-    else
-      USER_CMSSW_REPO=https://github.com/$GITHUB_USERNAME/cmssw.git
-    fi
+    OFFICIAL_CMSSW_REPO=`git config --get remote.official-cmssw.url || true`
+    USER_CMSSW_REPO=`git config --get remote.my-cmssw.url || true`
     LEADING_SLASH=/
   ;;
 esac
 
-if [ "X$CMSSW_GIT_REFERENCE" = X ]; then
-  case `hostname -f` in
-    *.cern.ch)
-      if [ -e /afs/cern.ch/cms/git-cmssw-mirror/cmssw.git ]; then
-        CMSSW_GIT_REFERENCE=/afs/cern.ch/cms/git-cmssw-mirror/cmssw.git
-      else
-        CMSSW_GIT_REFERENCE=~/.cmsgit-cache
-      fi
-    ;;
-    *) CMSSW_GIT_REFERENCE=~/.cmsgit-cache ;;
-  esac
-fi
-
-if [ ! -e $CMSSW_GIT_REFERENCE ]; then
-  while [ X$QUESTION_DONE = X ]; do
-    if [ X$ASSUME_YES = X ]; then
-      read -n 1 -p "Your reference git repository does not seem to exist, would you like to create it? [ y / N / ? ] "
-      QUESTION_DONE=1
-    else
-      REPLY=y
-      QUESTION_DONE=1
-    fi
-    case $REPLY in
-      y|Y|yes|YES)
-        git clone --bare $OFFICIAL_CMSSW_REPO $CMSSW_GIT_REFERENCE
-        touch $CMSSW_GIT_REFERENCE/create-`whoami`
-      ;;
-      [?])
-        echo
-        echo Answering yes will create a new cache directory in \$CMSSW_GIT_REFERENCE:
-        echo
-        echo i.e. $CMSSW_GIT_REFERENCE
-        echo
-        echo and put there a copy of the official CMSSW repository. git cms-addpkg will then
-        echo reuse this information to keep your CMSSW workareas to a minimal size.
-        echo The initial checkout could take a few minutes, but all the others should then
-        echo take only a few seconds.
-        echo
-        echo Just say yes.
-        echo
-        QUESTION_DONE=
-      ;;
-      *)
-        CMSSW_GIT_REFERENCE=none
-      ;;
-    esac
-  done
+# check if using a reference repository
+if [ "$CMSSW_GIT_REFERENCE" == "" ] && [ -f $CMSSW_BASE/src/.git/objects/info/alternates ]; then
+  CMSSW_GIT_REFERENCE=`cat .git/objects/info/alternates | head -n1`
 fi
 
 # if using a personal reference repository, update it from the official one
@@ -214,21 +101,16 @@ if [ -e $CMSSW_GIT_REFERENCE/create-`whoami` ]; then
   (cd $CMSSW_GIT_REFERENCE ;  git remote update origin 2>$VERBOSE_STREAM >$VERBOSE_STREAM)
 fi
 
-mkdir -p $CMSSW_BASE/src
-cd $CMSSW_BASE/src
+CMSSW_BRANCH=`git symbolic-ref --short HEAD`
+verbose You are on branch $CMSSW_BRANCH
 
-if [ ! -d "$CMSSW_BASE/src/.git" ]; then
-  # initialize the local repository
-  git cms-init $INITOPTIONS $CMSSW_TAG
-else
-  verbose You are on branch ${CMSSW_BASE_BRANCH}_X$SLHC
-  # refresh the local repository
-  [ -n "$CMSSW_MIRROR" ] && git remote set-url official-cmssw $CMSSW_MIRROR
-  git fetch official-cmssw        2> $VERBOSE_STREAM
-  git fetch official-cmssw --tags 2> $VERBOSE_STREAM
-  [ -n "$CMSSW_MIRROR" ] && git remote set-url official-cmssw $OFFICIAL_CMSSW_REPO
-fi
-verbose Checking out $PKG_NAME in tag $CMSSW_TAG.
+# refresh the local repository
+[ -n "$CMSSW_MIRROR" ] && git remote set-url official-cmssw $CMSSW_MIRROR
+git fetch official-cmssw        2> $VERBOSE_STREAM
+git fetch official-cmssw --tags 2> $VERBOSE_STREAM
+[ -n "$CMSSW_MIRROR" ] && git remote set-url official-cmssw $OFFICIAL_CMSSW_REPO
+
+verbose Checking out $PKG_NAME
 
 # add the requested package(s) to the sparse checkout
 cp -f $CMSSW_BASE/src/.git/info/sparse-checkout $CMSSW_BASE/src/.git/info/sparse-checkout-new
@@ -242,7 +124,7 @@ case $PKG_NAME in
   ;;
   *)
     if [ ! -d "$CMSSW_BASE/src/$PKG_NAME" ]; then
-      echo "Error: package $PKG_NAME does not exist in tag $CMSSW_TAG."
+      echo "Error: package $PKG_NAME does not exist in branch $CMSSW_BRANCH."
       exit 1
     fi
   ;;
