Ask for github username on first run.

diff --git a/git-cms-addpkg b/git-cms-addpkg
--- a/git-cms-addpkg
+++ b/git-cms-addpkg
@@ -51,6 +51,33 @@ while [ "$#" != 0 ]; do
   esac
 done
 
+GITHUB_USERNAME="`git config --global --get cms.github.user || true`"
+if [ "X$GITHUB_USERNAME" = X ]; then
+  echo "Cannot find your GitHub information."
+  echo "Please register at"
+  echo
+  echo "https://github.com"
+  echo
+  echo "and provide your username."
+  echo
+  GITHUB_USERNAME=
+  while [ "X$GITHUB_USERNAME" = X ]; do 
+    read -p "What is your github username? "
+    GITHUB_USERNAME=`echo $REPLY | sed -e 's/[ \t]*//g'`
+    # It is intended to not have "" around $GITHUB_USERNAME
+    if [ "X$GITHUB_USERNAME" = X ]; then
+      echo "You provided an empty string."
+    fi
+  done
+  echo
+  echo "Hello, $GITHUB_USERNAME, I will remember you on this computer now."
+  echo
+  echo "At any time you can change your information by doing."
+  echo
+  echo "git config --global cms.github.user $GITHUB_USERNAME"
+  git config --global cms.github.user $GITHUB_USERNAME
+fi
+
 if [ "X$CMSSW_BASE" = X ]; then
   echo CMSSW environment not setup. Do cmsenv in some workarea.
   exit 1
