Add force-create branch option.

diff --git a/git-cms-cherry-pick b/git-cms-cherry-pick
--- a/git-cms-cherry-pick
+++ b/git-cms-cherry-pick
@@ -2,11 +2,12 @@
 
 function usage() {
   cat <<@EOF
-Usage: git cms-cherry-pick <commit1>[..<commit2>] [--remote <remote>] [--create <branch>] [<cherry-pick optional arguments>]
+Usage: git cms-cherry-pick <commit1>[..<commit2>] [-r|--remote <remote>] [(-c|--create)|(-C|--force-create) <branch>] [<cherry-pick optional arguments>]
 
 Description:
   Cherry pick commit(s), ensuring modified subpackages are added before the commits are applied.
   The remote containing the commit(s) can be specified if not already present locally.
+  A new branch can be created before the cherry-picking takes place.
 @EOF
   exit $1
 }
@@ -36,6 +37,10 @@ while [[ $# -gt 0 ]]; do
             BRANCH="$2"
             shift; shift;
             ;;
+        -C|--force-create)
+            FORCE_BRANCH="$2"
+            shift; shift;
+            ;;
         [a-zA-Z0-9][a-zA-Z0-9\/\.\-][a-zA-Z0-9\/\.\-][a-zA-Z0-9\/\.\-][a-zA-Z0-9\/\.\-][a-zA-Z0-9\/\.\-][a-zA-Z0-9\/\.\-]*)
             COMMITS="$1"
             shift
@@ -59,9 +64,15 @@ if [ -n "$REMOTE" ]; then
     git fetch "$REMOTE"
 fi
 
-# move to a new branch
+# create a new branch before cherry-picking
+if [ -n "$BRANCH" ] && [ -n "$FORCE_BRANCH" ]; then
+    echo "fatal: options '-c' and '-C' cannot be used together"
+    exit 1
+fi
 if [ -n "$BRANCH" ]; then
     git switch -c "$BRANCH"
+elif [ -n "$FORCE_BRANCH" ]; then
+    git switch -C "$FORCE_BRANCH"
 fi
 
 # download modified subpackages
