implement addpkg -f behaviour

diff --git a/git-cms-addpkg b/git-cms-addpkg
--- a/git-cms-addpkg
+++ b/git-cms-addpkg
@@ -1,16 +1,18 @@
-#!/bin/sh -e
+#! /bin/bash -e
 # Mimics addpkg behavior in git.
-case `uname` in 
+case `uname` in
   Darwin) ECHO=echo ;;
   *) ECHO="echo -e" ;;
 esac
 usage () {
   echo "git cms-addpkg [options] SubSystem/Package"
+  echo "git cms-addpkg [options] -f FILE"
   echo
   echo "Options:"
   $ECHO "-h                 \tthis help message"
   $ECHO
   $ECHO "-d, --debug        \tenable debug output"
+  $ECHO "-f, --file FILE    \tread the list of packages to be checkoed out from FILE"
   $ECHO "    --https        \tuse https, rather than ssh to access your personal repository"
   $ECHO "    --ssh          \tuse ssh, rather than https to access the official repository"
   $ECHO "-z, --quiet        \tdo not print out progress"
@@ -31,6 +33,7 @@ verbose () {
 
 PKG_NAME=
 CMSSW_TAG=
+INPUT_FILE=
 while [ "$#" != 0 ]; do
   case "$1" in
     -h | --help )
@@ -38,6 +41,20 @@ while [ "$#" != 0 ]; do
     -d | --debug )
       INITOPTIONS="$INITOPTIONS $1"
       shift; set -x; DEBUG_STREAM=/dev/stderr ;;
+    -f | --file )
+      OPTION=$1; shift
+      INPUT_FILE="$1"; shift
+      if [ ! "$INPUT_FILE" ]; then
+        $ECHO "git cms-addpkg: option $OPTION requires an argument"
+        $ECHO
+        usage 1
+      elif [ ! -r "$INPUT_FILE" ]; then
+        $ECHO "git cms-addpkg: file $INPUT_FILE does not exist or is not readable"
+        $ECHO
+        usage 1
+      fi
+      unset OPTION
+      ;;
     -q | --quiet )
       INITOPTIONS="$INITOPTIONS $1"
       shift; set +x; VERBOSE=0; VERBOSE_STREAM=/dev/null ;;
@@ -53,17 +70,31 @@ while [ "$#" != 0 ]; do
     -*)
       echo Unknown option $1 ; usage 1 ;;
     *)
-      if [ "X$PKG_NAME" = X ]; then
-        PKG_NAME=$1
-      elif [ "X$CMSSW_TAG" = X ]; then
-        CMSSW_TAG=$1
+      if [ "$INPUT_FILE" == "" ]; then
+        # check out a single package
+        if [ "X$PKG_NAME" = X ]; then
+          PKG_NAME=$1
+        elif [ "X$CMSSW_TAG" = X ]; then
+          CMSSW_TAG=$1
+        else
+          echo "git cms-addpkg: you can specify only one package at the time." ; exit 1
+        fi
+        shift 1
       else
-        echo "You can specify only one package at the time." ; exit 1
+        # check out a list of packages via -f / --file FILE
+        if [ "X$CMSSW_TAG" = X ]; then
+          CMSSW_TAG=$1
+        else
+          echo "git cms-addpkg: you cannot specify a package and input from file at the same time." ; exit 1
+        fi
       fi
-      shift 1
     ;;
   esac
 done
+
+if [ "$PKG_NAME" == "" ] && [ "$INPUT_FILE" == "" ] ; then
+  echo "You need to specify at least one package or input file." ; exit 1
+fi
 
 GITHUB_USERNAME="`git config --global --get user.github || true`"
 if [ "X$GITHUB_USERNAME" = X ]; then
@@ -95,10 +126,6 @@ if [ "X$USER_EMAIL" = X ]; then
 fi
 
 
-if [ "X$PKG_NAME" = X ]; then
-  echo "You need to specify at least one package." ; exit 1 
-fi
-
 if [ "X$CMSSW_BASE" = X ]; then
   if [ "X$CMSSW_TAG" = X ]; then
     verbose CMSSW environment not setup. Do cmsenv in some workarea or specify tag to checkout.
@@ -117,7 +144,7 @@ fi
 CMSSW_BASE_BRANCH=`echo $CMSSW_TAG | sed -e 's/\(CMSSW_[0-9][0-9]*_[0-9][0-9]*\).*/\1/'`
 
 # SLHC releases
-case $CMSSW_TAG in 
+case $CMSSW_TAG in
   *_SLHC*)
     SLHC=_SLHC ;;
 esac
@@ -132,13 +159,13 @@ esac
 #    echo git cms-addpkg must be run from inside a CMSSW area.
 #    exit 1
 #  else
-#    echo Error: You have currently set up the environment of $OLD_CMSSW_BASE, however you are running inside $CMSSW_BASE.
+#    echo git cms-addpkg: You have currently set up the environment of $OLD_CMSSW_BASE, however you are running inside $CMSSW_BASE.
 #    echo Please go inside $OLD_CMSSW_BASE, or use cmsenv to switch to $CMSSW_BASE.
 #    exit 1
 #  fi
 #fi
 
-case `git --version` in 
+case `git --version` in
   git\ version\ 1.7*)
     OFFICIAL_CMSSW_REPO=git@github.com:cms-sw/cmssw.git
     USER_CMSSW_REPO=git@github.com:$GITHUB_USERNAME/cmssw.git
@@ -227,13 +254,27 @@ else
   git fetch official-cmssw --tags 2> $VERBOSE_STREAM
   [ -n "$CMSSW_MIRROR" ] && git remote set-url official-cmssw $OFFICIAL_CMSSW_REPO
 fi
-verbose Checking out $PKG_NAME in tag $CMSSW_TAG.
 
-# add the requested package(s) to the sparse checkout
-cp -f $CMSSW_BASE/src/.git/info/sparse-checkout $CMSSW_BASE/src/.git/info/sparse-checkout-new
-echo "$PKG_NAME" | sed -e "s|[/]*$|/|;s|^/*|${LEADING_SLASH}|" >> $CMSSW_BASE/src/.git/info/sparse-checkout-new
-cat .git/info/sparse-checkout-new | sort -u > $CMSSW_BASE/src/.git/info/sparse-checkout
-rm -f .git/info/sparse-checkout-new
+if [ "$INPUT_FILE" ]; then
+  verbose "Checking out packages in tag $CMSSW_TAG:"
+  verbose "$(< "$INPUT_FILE")"
+
+  # FIXME check the syntax of the input file ?
+
+  # add the requested package(s) to the sparse checkout
+  cp -f $CMSSW_BASE/src/.git/info/sparse-checkout $CMSSW_BASE/src/.git/info/sparse-checkout-new
+  cat "$INPUT_FILE" | sed -e "s|[/]*$|/|;s|^/*|${LEADING_SLASH}|" >> $CMSSW_BASE/src/.git/info/sparse-checkout-new
+  cat .git/info/sparse-checkout-new | sort -u > $CMSSW_BASE/src/.git/info/sparse-checkout
+  rm -f .git/info/sparse-checkout-new
+else
+  verbose "Checking out $PKG_NAME in tag $CMSSW_TAG."
+
+  # add the requested package(s) to the sparse checkout
+  cp -f $CMSSW_BASE/src/.git/info/sparse-checkout $CMSSW_BASE/src/.git/info/sparse-checkout-new
+  echo "$PKG_NAME" | sed -e "s|[/]*$|/|;s|^/*|${LEADING_SLASH}|" >> $CMSSW_BASE/src/.git/info/sparse-checkout-new
+  cat .git/info/sparse-checkout-new | sort -u > $CMSSW_BASE/src/.git/info/sparse-checkout
+  rm -f .git/info/sparse-checkout-new
+fi
 
 #cd $CMSSW_BASE/src
 #if [ "X`git show-ref $CMSSW_TAG || true`"  = X ]; then
@@ -262,12 +303,12 @@ rm -f .git/info/sparse-checkout-new
 #fi
 
 git read-tree -mu HEAD
-case $PKG_NAME in 
+case $PKG_NAME in
   *[*]* )
   ;;
   *)
     if [ ! -d "$CMSSW_BASE/src/$PKG_NAME" ]; then
-      echo "Error: package $PKG_NAME does not exist in tag $CMSSW_TAG."
+      echo "git cms-addpkg: package $PKG_NAME does not exist in tag $CMSSW_TAG."
       exit 1
     fi
   ;;
