add no-merge option for cms-merge-topic

diff --git a/git-cms-merge-topic b/git-cms-merge-topic
--- a/git-cms-merge-topic
+++ b/git-cms-merge-topic
@@ -18,6 +18,7 @@ usage() {
   $ECHO "-s, --strategy     \tspecify strategy when merging"
   $ECHO "-X, --strategy-option     \tspecify strategy when merging"
   $ECHO "-u, --unsafe       \tdo not perform checkdeps at the end"
+  $ECHO "-n, --no-merge       \tdo not perform a merge, just checkout code from specified branch"
   exit 1
 }
 
@@ -32,6 +33,10 @@ while [ $# -gt 0 ]; do
   case $1 in 
     -u|--unsafe)
       UNSAFE=true
+      shift
+      ;;
+    -n|--no-merge)
+      NOMERGE=true
       shift
       ;;
     -d|--debug)
@@ -71,12 +76,15 @@ while [ $# -gt 0 ]; do
       # - Pull request: `<pull-request-id>`
       GITHUB_USER=cms-sw ; 
       BRANCH=$1 ;
+      LOCAL_BRANCH=$1 ;
       case $1 in
         *:*)
           BRANCH=`echo $1 | cut -f2 -d:`
+          LOCAL_BRANCH=$BRANCH
           GITHUB_USER=`echo $1 | cut -f1 -d:` ;;
         [0-9]*) 
-          BRANCH=refs/pull/$1/head ;; 
+          BRANCH=refs/pull/$1/head 
+          LOCAL_BRANCH=PR$1 ;; 
       esac ;
       shift
     ;;
@@ -118,6 +126,11 @@ fi
 
 PULL_ID=$1
 
+TEMP_BRANCH=merge-attempt
+if [ "X$NOMERGE" = Xtrue ]; then
+  TEMP_BRANCH=checkout-attempt
+fi
+
 # initialize the local repository
 if [ -z "$CMSSW_BASE" ]; then
   echo "CMSSW environment not setup, please run 'cmsenv' before 'git cms-merge-topic'."
@@ -128,7 +141,7 @@ if ! [ -d $CMSSW_BASE/src/.git ]; then
 fi
 
 cd $CMSSW_BASE/src
-git fetch . +HEAD:merge-attempt || { echo "You are on a failed merge branch. Do \"git branch\" and checkout the one you were on."; exit 1; }
+git fetch . +HEAD:$TEMP_BRANCH || { echo "You are on a failed merge branch. Do \"git branch\" and checkout the one you were on."; exit 1; }
 
 if [ "$(git status --porcelain --untracked=no | grep '^[ACDMRU]')" ]; then
   $ECHO "${RED}Error:${NORMAL} there are staged but not committed changes on your working tree, please commit or stash them."
@@ -148,26 +161,33 @@ if [ -z "$COMMIT" ]; then
 fi
 
 # Fetch the branch specified from github and replace merge-attempt with it. 
-# The + is used to force the merge-attampt branch to be updated.
+# The + is used to force the merge-attempt branch to be updated.
 git fetch -n $REPOSITORY +$COMMIT:$GITHUB_USER/$BRANCH
 # Save the name of the current branch.
 CURRENT_BRANCH=`git rev-parse --abbrev-ref HEAD`
 # Attempt a merge in a separate branch
-git checkout merge-attempt >&${debug}
+git checkout $TEMP_BRANCH >&${debug}
 MERGE_BASE=`git merge-base $GITHUB_USER/$BRANCH $CURRENT_BRANCH`
 git cms-sparse-checkout $DEBUG_OPT $MERGE_BASE $GITHUB_USER/$BRANCH
 git read-tree -mu HEAD
-git merge $NO_COMMIT $MERGE_STRATEGY $STRATEGY_OPTION --no-ff -m "Merged $BRANCH from repository $GITHUB_USER" $GITHUB_USER/$BRANCH || { echo "Unable to merge branch $BRANCH from repository $GITHUB_USER." ; exit 1; }
-if [ ! X$NO_COMMIT = X ]; then
-  echo \"--no-commit\" specified: not committing and leaving you on the merge-attempt branch.\n Use git-status to check changes. ; exit 0
+# in no-merge case, just checkout a new branch
+if [ "X$NOMERGE" = Xtrue ]; then
+  git checkout -b $LOCAL_BRANCH $GITHUB_USER/$BRANCH
+  echo "Created branch $LOCAL_BRANCH to follow $BRANCH from repository $GITHUB_USER"
+# otherwise, perform merge
+else
+  git merge $NO_COMMIT $MERGE_STRATEGY $STRATEGY_OPTION --no-ff -m "Merged $BRANCH from repository $GITHUB_USER" $GITHUB_USER/$BRANCH || { echo "Unable to merge branch $BRANCH from repository $GITHUB_USER." ; exit 1; }
+  if [ ! X$NO_COMMIT = X ]; then
+    echo \"--no-commit\" specified: not committing and leaving you on the $TEMP_BRANCH branch.\n Use git-status to check changes. ; exit 0
+  fi
+  git checkout $CURRENT_BRANCH 
+  # Add the missing files.
+  git read-tree -mu HEAD
+  # This should always be a FF commit.
+  git merge --ff $TEMP_BRANCH >&${debug}
 fi
-git checkout $CURRENT_BRANCH 
-# Add the missing files.
-git read-tree -mu HEAD
-# This should always be a FF commit.
-git merge --ff merge-attempt >&${debug}
 # Delete the branch used for merge
-git branch -D merge-attempt >&${debug} || true
+git branch -D $TEMP_BRANCH >&${debug} || true
 # Do checkdeps unless not specified.
 if [ ! "X$UNSAFE" = Xtrue ]; then
   git cms-checkdeps -a
