check the syntax of the input file

diff --git a/git-cms-addpkg b/git-cms-addpkg
--- a/git-cms-addpkg
+++ b/git-cms-addpkg
@@ -138,7 +138,14 @@ if [ "$INPUT_FILE" ]; then
   verbose "Checking out packages"
   verbose "`cat "$INPUT_FILE"`"
 
-  # FIXME check the syntax of the input file ?
+  # check the syntax of the input file
+  INVALID=`cat "$INPUT_FILE" | grep -v '^#' | grep -v '^\s*$' | grep -v -E '^/*\w+(/\w+)?/*$'`
+  if [ $? == 0 ]
+    echo "Some lines of $INPUT_FILE are not in a valid format:"
+    echo "$INVALID"
+    exit 1
+  fi
+  unset INVALID
 
   # add the requested package(s) to the sparse checkout
   cp -f $CMSSW_BASE/src/.git/info/sparse-checkout $CMSSW_BASE/src/.git/info/sparse-checkout-new
